
version: "3.8"
services:
  backend:
    build: ./
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db:27017/CarShop
    depends_on:
      - "db"
    restart: always
  db:
    image: mongo:4.4.1
    container_name: db
    ports:
      - 3002:27017
    environment:
      MONGO_INITDB_DATABASE: CarShop
    restart: 'always'
